// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimsoftSignature.Infrastructure.Persistence;

#nullable disable

namespace TimsoftSignature.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimsoftSignature.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nom");

                    b.HasKey("Id");

                    b.ToTable("Departements", (string)null);
                });

            modelBuilder.Entity("TimsoftSignature.Domain.Entities.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenuHTML")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContenuHTML");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartementId");

                    b.Property<string>("SignatureName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomSignature");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Statut");

                    b.Property<int>("TypeTemplate")
                        .HasColumnType("int")
                        .HasColumnName("TypeTemplate");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Signatures", (string)null);
                });

            modelBuilder.Entity("TimsoftSignature.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Adresse");

                    b.Property<string>("BusinessEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailPro");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomEntreprise");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartementId");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Prenom");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Instagram");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nom");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LinkedIn");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LogoUrl");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TelMobile");

                    b.Property<string>("OfficePhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TelBureau");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MotDePasse");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhotoUrl");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Poste");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SiteWeb");

                    b.Property<string>("YoutubeUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Youtube");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Utilisateurs", (string)null);
                });

            modelBuilder.Entity("TimsoftSignature.Domain.Entities.Signature", b =>
                {
                    b.HasOne("TimsoftSignature.Domain.Entities.Department", "Department")
                        .WithMany("Signatures")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TimsoftSignature.Domain.Entities.User", b =>
                {
                    b.HasOne("TimsoftSignature.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TimsoftSignature.Domain.Entities.Department", b =>
                {
                    b.Navigation("Signatures");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
